import "./user"
import "./chatbox"
import "./comment"
import "./ticket_types"
import "./search"
import "./favorite"
import "./qr_code"
import "./qr_code_reader"
import "qrcode"
import "./attand_list"
import "./attand_event"
import "./seat"
// import "./swiper"
import "./checkbox"
import "./rubytix"
