 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/chatrooms", type: :request do
  # Chatroom. As you add validations to Chatroom, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Chatroom.create! valid_attributes
      get chatrooms_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      chatroom = Chatroom.create! valid_attributes
      get chatroom_url(chatroom)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_chatroom_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      chatroom = Chatroom.create! valid_attributes
      get edit_chatroom_url(chatroom)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Chatroom" do
        expect {
          post chatrooms_url, params: { chatroom: valid_attributes }
        }.to change(Chatroom, :count).by(1)
      end

      it "redirects to the created chatroom" do
        post chatrooms_url, params: { chatroom: valid_attributes }
        expect(response).to redirect_to(chatroom_url(Chatroom.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Chatroom" do
        expect {
          post chatrooms_url, params: { chatroom: invalid_attributes }
        }.to change(Chatroom, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post chatrooms_url, params: { chatroom: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested chatroom" do
        chatroom = Chatroom.create! valid_attributes
        patch chatroom_url(chatroom), params: { chatroom: new_attributes }
        chatroom.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the chatroom" do
        chatroom = Chatroom.create! valid_attributes
        patch chatroom_url(chatroom), params: { chatroom: new_attributes }
        chatroom.reload
        expect(response).to redirect_to(chatroom_url(chatroom))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        chatroom = Chatroom.create! valid_attributes
        patch chatroom_url(chatroom), params: { chatroom: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested chatroom" do
      chatroom = Chatroom.create! valid_attributes
      expect {
        delete chatroom_url(chatroom)
      }.to change(Chatroom, :count).by(-1)
    end

    it "redirects to the chatrooms list" do
      chatroom = Chatroom.create! valid_attributes
      delete chatroom_url(chatroom)
      expect(response).to redirect_to(chatrooms_url)
    end
  end
end
